# Generated by Django 2.2.13 on 2020-11-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_obj', models.CharField(max_length=50, verbose_name='城市名称')),
                ('view_address', models.CharField(max_length=200, verbose_name='景点地点')),
                ('view_score', models.CharField(max_length=20, verbose_name='景点分数')),
                ('view_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='票价')),
                ('view_name', models.CharField(max_length=50, verbose_name='景点名称')),
                ('view_img', models.CharField(max_length=400, verbose_name='景点图片')),
            ],
        ),
    ]
