# Generated by Django 2.2.13 on 2020-11-08 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, verbose_name='订单编号')),
                ('trade_no', models.CharField(max_length=100, verbose_name='支付宝交易编号')),
                ('order_status', models.CharField(max_length=60, verbose_name='支付结果')),
                ('order_buytime', models.DateField(auto_now_add=True, verbose_name='购买日期')),
                ('spend_buytime', models.DateField(verbose_name='消费日期')),
                ('is_consumed', models.BooleanField(default=False, verbose_name='是否已消费')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile')),
            ],
        ),
    ]
